### ISSUE TITLE
Problem with http://aznhusband.github.io/repo

### ISSUE THREAD

**Issue by tofufi** [aznhusband/aznhusband.github.io#42]
i install http://aznhusband.github.io/repo with kodi for 2 yrs But. It is not functioning since yesterday night. Is anyone have same issue?

http://aznhusband.github.io/repo

thanks!

**Comment by aznhusband** [comment]
Yes, something's changed, I'll have to have a look over the weekend.

**Comment by tofufi** [comment]
Great thanks
Take your time.

**Comment by jcheong-1** [comment]
It appears to me that for people who are on the new urlresolver version 5+ the addon still works.

I've updated urlresolver to 5.0.48 and icdrama addon works.

But since TVAddons took over for urlresolver they now force install Indigo as a dependency whenever you install urlresolver

Would it be possible to update icdrama to use ResolveURL instead of URLResolver?

Thanks!

**Comment by aznhusband** [comment]
Seems like a good option, I'll work towards that.

**Comment by jcheong-1** [comment]
thanks aznhusband that will be fantastic!

**Comment by gumpwa** [comment]
Wouldn't the easiest fix be to just update to use urlresolver  5.0.48?

**Comment by jcheong-1** [comment]
Yes and no, yes for short term fix which all users can do themselves. No because URLResolver has now changed hands.

URLResolver starting from version 5.0.50 after TVAddons took over force install Indigo (their own app) as a dependency without users acknowledgement. Most people consider that as spyware/malware and don't like it.

URLResolver copies the changes from ResolveURL anyways, might as well use the clean source

**Comment by aznhusband** [comment]
OK, moved to ResolveURL.  Fixed in 2.0.1, Once I get some reports of people using the new version successfully, I'll close this bug.

**Comment by gti96** [comment]
I just tried 2.0.1 and it's still showing URLResolver as dependencies and ResolveURL is not there.

**Comment by paullew** [comment]
Thanks for the update! 

I'm having trouble installing the update to 2.0.1 - I think my kodi doesn't know where to install resolveurl from. Here's a screenshot:

![image](https://user-images.githubusercontent.com/147187/82113235-d7869a00-9797-11ea-9fc0-0efacec21d8f.png)

Do I need to install resolveurl manually, or do I need to install another repo?

**Comment by aznhusband** [comment]
Yeah, I mention that on the https://aznhusband.github.io site; you need to re-install the repo so that it'll point to where to pick up ResolveURL.  I'm basically providing a pointer to the jsergio repo in my repo, so you'll automatically pull in the latest release of ResolveURL.

Glad it's working for you.

**Comment by aznhusband** [comment]
You need to re-install the repo; download the repo-1.1.1, so it can find the ResolveURL reference.

 

See https://aznhusband.github.io

 
 

Sent: Saturday, May 16, 2020 at 2:09 AM

**Comment by decantur** [comment]
We run three instances - uninstalling and reinstalling the repo updates to 2.0.1 and fixes the issue. Also, the ResolveURL dependency is now present.

Thanks so much.

**Comment by jcheong-1** [comment]
Thank you so much!

I've done the following to update and this seems to work well.

1. Remove the old icdrama completely
2. Uninstall the old repo
3. Install the new repo
4. Install the new icdrama addon

Working welll, thanks again!

**Comment by tofufi** [comment]
Works again.
my kodi 15.2 in Canada

Thanks!!!!!

**Comment by aznhusband** [comment]
K, lots of people reporting the new version works fine, so gonna close this bug.

**Comment by gti96** [comment]
Thanks. Previously when I tried the repo was still showing only having 1.9.6 and thus I tried from plugin.video.Icdrama to make it 2.0.1. Now it is fully working. Thanks a lot!
